name: Nuxt Generate

on: [push, pull_request]

env:
  NODE_ENV: production

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - run: npm ci
      - run: npm run git:submodules:add
      - run: node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.mjs generate
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist