name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - run: npm ci
      - shell: bash
        run: git submodule add -f https://github.com/open-dictionary/english-dictionary.git node_modules/english-dictionary
      - run: npm run generate
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist